### ISSUE TITLE
Some channels don't work suddenly

### ISSUE THREAD

**Issue by michalcs** [cvb941/magiogo-iptv-server#10]
Zdravim, Hello

Sometime since early August I started noticing some channels not working anymore. Namely `Film Europe HD`. I went in to check the source URL it's resolving to and it yielded 404.

There are a few more channels affected by this, but not all. And they all work with no problems in [Saros' script](https://github.com/Saros72/TV-GO-Playlist).

Any chance to take a look please. Thanks 🙏

**Comment by michalcs** [comment]
Premium channels still don't work. Hmmm. What a pity…

**Comment by cvb941** [comment]
Pozrel som sa na to a vyzerá že `Film Europe HD` funguje iba na MEDIUM kvalite.

**Comment by cvb941** [comment]
@michalcs Skús najnovšiu verziu, už by to malo fungovať

**Comment by michalcs** [comment]
Funguje! Super, diky 🙌
