### ISSUE TITLE
Ako to spustiť 

### ISSUE THREAD

**Issue by Radoorech** [cvb941/magiogo-iptv-server#13]
Zdravím,
Chcem sa Vás opýtať ako funguje tento server? Poradíte ako to spustiť na Coreelec, prípadne iný spôsob v Kodi?
Ďakujem za prípadnú odpoveď a popis postupu.
Rado.

**Comment by cvb941** [comment]
Tento server funguje samostatne a generuje iba .m3u8 playlisty a XMLTV guide.
Pre použitie priamo v Kodi bude asi lepší napríklad [tento addon](https://www.xbmc-kodi.cz/prispevek-tv-go-playlist-v1-16-4?pid=104731).

**Comment by Radoorech** [comment]
Ďakujem za odpoveď,
Ten addon, ktorý ste mi poradili samozrejme poznám, ale ten generuje playlist a epg trochu inak.
Mňa preto zaujalo, že vy to máte ako server, preto to chcem vyskúšať, ale neviem ako na to.
Čo k tomu, aby som to spustil potrebujem, ako postupovať.

**Comment by cvb941** [comment]
Neviem takto povedať, ako by som tento projekt rozchodil v Kodi, ale ak ho chcete vyskúšať na svojom PC tak stačí mať nainštalovaný Python a pustiť na Windowse v cmd [tieto príkazy](https://github.com/cvb941/magiogo-iptv-server#python) so správnym loginom.

Do konzole by sa potom mal vyprintovať link na jednoduchú info stránku servera, kde je zase link na vygenerovaný .m3u8 playlist. Ten sa dá stiahnuť a pustiť priamo napríklad vo VLC prehrávači (Ctrl+L zobrazí zoznam kanálov).

**Comment by Radoorech** [comment]
Ďakujem za ochotu a odpoveď, skúsim to na notebooku a uvidím či mi to pôjde.
